name: QuickPic
options:
  bundleIdPrefix: com.quickpic
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.4"
  minimumXcodeGenVersion: "2.0"

settings:
  DEVELOPMENT_TEAM: ""

targets:
  QuickPic:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Services
      - Views
    resources:
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.quickpic.app
      INFOPLIST_GENERATION_MODE: GeneratedFile
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
