name: QuickPic
options:
  bundleIdPrefix: sh.reece
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "26.0"
  minimumXcodeGenVersion: "2.42"

settings:
  DEVELOPMENT_TEAM: ""

targets:
  QuickPic:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Services
      - Views
    resources:
      - Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: sh.reece.quickpic
      INFOPLIST_GENERATION_MODE: GeneratedFile
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "6.0"
